# Generated by Django 3.0 on 2019-12-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='onwer',
            new_name='owner',
        ),
    ]
